# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 460)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.inputValidaCpf = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(20)
        self.inputValidaCpf.setFont(font)
        self.inputValidaCpf.setStyleSheet("color: green")
        self.inputValidaCpf.setAlignment(QtCore.Qt.AlignCenter)
        self.inputValidaCpf.setObjectName("inputValidaCpf")
        self.gridLayout.addWidget(self.inputValidaCpf, 0, 3, 1, 1)
        self.btnValidaCpf = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidaCpf.setMinimumSize(QtCore.QSize(200, 5))
        self.btnValidaCpf.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.btnValidaCpf.setFont(font)
        self.btnValidaCpf.setObjectName("btnValidaCpf")
        self.gridLayout.addWidget(self.btnValidaCpf, 0, 4, 1, 1)
        self.btnGeraCpf = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.btnGeraCpf.setFont(font)
        self.btnGeraCpf.setObjectName("btnGeraCpf")
        self.gridLayout.addWidget(self.btnGeraCpf, 4, 3, 1, 1)
        self.labelRetorno = QtWidgets.QLineEdit(self.centralwidget)
        self.labelRetorno.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRetorno.sizePolicy().hasHeightForWidth())
        self.labelRetorno.setSizePolicy(sizePolicy)
        self.labelRetorno.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelRetorno.setFont(font)
        self.labelRetorno.setStyleSheet("color: green")
        self.labelRetorno.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRetorno.setReadOnly(True)
        self.labelRetorno.setObjectName("labelRetorno")
        self.gridLayout.addWidget(self.labelRetorno, 2, 2, 1, 2, QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GERADOR DE CPF"))
        self.label_2.setText(_translate("MainWindow", "Valida CPF:"))
        self.btnValidaCpf.setText(_translate("MainWindow", "Validar"))
        self.btnGeraCpf.setText(_translate("MainWindow", "Gerar CPF"))
        self.labelRetorno.setText(_translate("MainWindow", "833.091.466-69"))
